// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD522FSIKNXutf62FMuLqxgp_g6q3Sdxbs',
    appId: '1:174018964568:web:7d48937abd27aa80d4ee2d',
    messagingSenderId: '174018964568',
    projectId: 'kartik-reddit-clone',
    authDomain: 'kartik-reddit-clone.firebaseapp.com',
    storageBucket: 'kartik-reddit-clone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_yYkUSsUNVlIF0kldyzIunQ5R8dYifng',
    appId: '1:174018964568:android:326f0ab6aa924512d4ee2d',
    messagingSenderId: '174018964568',
    projectId: 'kartik-reddit-clone',
    storageBucket: 'kartik-reddit-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGkBSFvwcfi9pctEy15Q5Bj8aRCsK0nio',
    appId: '1:174018964568:ios:c178530ecbd32fe0d4ee2d',
    messagingSenderId: '174018964568',
    projectId: 'kartik-reddit-clone',
    storageBucket: 'kartik-reddit-clone.appspot.com',
    iosBundleId: 'com.example.redditClone',
  );
}
